"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { ProgressTracker } from "@/components/ProgressTracker";
import { AdGallery, CompetitorAdGallery } from "@/components/AdGallery";
import { ConceptCards } from "@/components/ConceptCards";
import { CreativeGallery } from "@/components/CreativeGallery";
import type { Job } from "@/lib/types";

// 1-pager view. Heavy reports (full brand profile, exhaustive VoC, multi-
// field diagnosis prose) are still generated by the pipeline and live on
// the Job — they just aren't surfaced here. Once auth/dashboard is in
// (Phase 3+), the deep view is a click away. This page = the agency
// hand-off that founders actually read.
const SECTIONS: { id: string; num: string; label: string }[] = [
  { id: "brand", num: "01", label: "Your brand" },
  { id: "ads", num: "02", label: "Your ads" },
  { id: "rivals", num: "03", label: "Rivals" },
  { id: "diagnosis", num: "04", label: "Diagnosis" },
  { id: "voc", num: "05", label: "Customer voice" },
  { id: "plan", num: "06", label: "The plan" },
];

export default function AnalyzePage() {
  const params = useParams();
  const jobId = params.jobId as string;
  const isMockJob = jobId.startsWith("mock-");
  const [job, setJob] = useState<Job | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [activeId, setActiveId] = useState<string>("ads");
  const [now, setNow] = useState(() => Date.now());
  const rootRef = useRef<HTMLElement | null>(null);
  const advancingRef = useRef(false);

  const fetchJob = useCallback(async () => {
    try {
      const res = await fetch(`/api/jobs/${jobId}`);
      if (!res.ok) {
        setError("Job not found");
        return;
      }
      const data = await res.json();
      setJob(data);
    } catch {
      setError("Failed to fetch job status");
    }
  }, [jobId]);

  useEffect(() => {
    fetchJob();
    const clock = setInterval(() => setNow(Date.now()), 1000);
    const interval = setInterval(() => {
      if (
        job?.status === "complete" ||
        job?.status === "awaiting-approval" ||
        job?.status === "error"
      ) {
        clearInterval(interval);
        return;
      }
      fetchJob();
    }, 2000);
    return () => {
      clearInterval(clock);
      clearInterval(interval);
    };
  }, [fetchJob, job?.status]);

  useEffect(() => {
    if (
      !job ||
      job.status === "complete" ||
      job.status === "awaiting-approval" ||
      job.status === "error" ||
      isMockJob ||
      advancingRef.current
    ) {
      return;
    }

    const justStartedScanner =
      job.status === "scraping-website" &&
      job.progress.length <= 1 &&
      Date.now() - new Date(job.createdAt).getTime() < 10_000;
    if (justStartedScanner) return;

    let cancelled = false;
    const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

    async function advanceUntilDone() {
      advancingRef.current = true;
      try {
        while (!cancelled) {
          const res = await fetch(`/api/jobs/${jobId}/advance`, {
            method: "POST",
          });
          const data = (await res.json().catch(() => ({}))) as {
            done?: boolean;
            status?: Job["status"];
          };

          await fetchJob();

          if (
            !res.ok ||
            data.done ||
            data.status === "complete" ||
            data.status === "awaiting-approval" ||
            data.status === "error"
          ) {
            break;
          }

          await delay(250);
        }
      } catch (err) {
        console.error("[analyze] advance failed; polling will keep retrying", err);
        await delay(2000);
      } finally {
        advancingRef.current = false;
      }
    }

    void advanceUntilDone();
    return () => {
      cancelled = true;
    };
  }, [fetchJob, isMockJob, job, jobId]);

  useEffect(() => {
    if (job?.status !== "complete" && job?.status !== "awaiting-approval") return;
    const root = rootRef.current;
    if (!root) return;

    const revealTargets = root.querySelectorAll<HTMLElement>("[data-reveal]");
    const revealIO = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.isIntersecting) {
            e.target.classList.add("in-view");
            revealIO.unobserve(e.target);
          }
        }
      },
      { rootMargin: "0px 0px -15% 0px", threshold: 0.12 }
    );
    revealTargets.forEach((el) => revealIO.observe(el));

    const activeTargets = SECTIONS.map((s) =>
      document.getElementById(s.id)
    ).filter((el): el is HTMLElement => !!el);
    const activeIO = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((e) => e.isIntersecting)
          .sort((a, b) => (a.target as HTMLElement).offsetTop - (b.target as HTMLElement).offsetTop);
        if (visible[0]) setActiveId(visible[0].target.id);
      },
      { rootMargin: "-40% 0px -50% 0px", threshold: 0 }
    );
    activeTargets.forEach((el) => activeIO.observe(el));

    return () => {
      revealIO.disconnect();
      activeIO.disconnect();
    };
  }, [job?.status]);

  if (error) {
    return (
      <main className="min-h-screen bg-paper flex items-center justify-center">
        <div className="text-center">
          <div className="eyebrow text-ink/60">404</div>
          <h1 className="font-semibold mt-3 text-4xl">We couldn’t find that job.</h1>
          <p className="mt-3 text-ink/60">{error}</p>
          <Link href="/" className="btn-chunk mt-6 inline-flex">← Start a new diagnosis</Link>
        </div>
      </main>
    );
  }

  if (!job) {
    return (
      <main className="min-h-screen bg-paper flex items-center justify-center">
        <div className="h-5 w-5 animate-spin rounded-full border-2 border-coral border-t-transparent" />
      </main>
    );
  }

  if (job.status !== "complete" && job.status !== "awaiting-approval") {
    return (
      <main className="min-h-screen bg-paper">
        <div className="mx-auto max-w-2xl px-4">
          <ProgressTracker
            jobId={job.id}
            status={job.status}
            progress={job.progress}
            error={job.error}
            now={now}
          />
        </div>
      </main>
    );
  }

  const company = job.input?.companyName || "this company";
  const topConcepts = (job.concepts || []).slice(0, 3);
  const topCreatives = (job.creatives || []).slice(0, 3);
  const topQuotes = (job.voc?.snippets || []).slice(0, 4);

  return (
    <main ref={rootRef} className="min-h-screen bg-paper text-ink">
      <ProgressRail activeId={activeId} />

      <header className="sticky top-0 z-20 border-b hairline bg-paper/85 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-6 px-5 py-4">
          <Link href="/" className="flex items-baseline gap-[2px] font-serif text-[1.15rem] leading-none">
            <span className="italic">better</span>
            <span className="italic text-coral">your</span>
            <span className="italic">ads</span>
            <span className="ml-1 inline-block h-1.5 w-1.5 translate-y-[-2px] rounded-full bg-coral" />
          </Link>
          <div className="hidden flex-1 items-baseline gap-3 md:flex">
            <span className="font-mono text-[0.7rem] uppercase tracking-[0.2em] text-ink/45">
              analysis for
            </span>
            <span className="font-semibold text-lg text-ink">{company}</span>
          </div>
          <nav className="hidden items-center gap-6 text-sm md:flex">
            {SECTIONS.map((s) => (
              <a
                key={s.id}
                href={`#${s.id}`}
                className="link-underline text-ink/70 hover:text-ink"
              >
                {s.label}
              </a>
            ))}
          </nav>
        </div>
      </header>

      {/* Verdict masthead — the whole diagnosis in 4 lines */}
      <section data-reveal className="border-b hairline">
        <div className="mx-auto max-w-6xl px-5 py-16 md:py-24">
          <div className="eyebrow text-ink/55">
            The verdict · {new Date(job.completedAt || Date.now()).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" })}
          </div>
          <h1 className="display mt-5 max-w-4xl text-[clamp(2.5rem,6vw,5.25rem)]">
            What’s happening with{" "}
            <span className="display-italic text-coral">{company}</span>’s ads.
          </h1>
          {job.diagnosis?.tldr && <TldrInline tldr={job.diagnosis.tldr} />}
        </div>
      </section>

      <div className="mx-auto max-w-6xl px-5">
        {(job.brandProfile || job.websiteScreenshot) && (
          <Section
            num="01"
            label="Your brand"
            id="brand"
            title="What we {em} from your site."
            emphasis="captured"
            kicker="Colors, fonts, and the hero we used as the source of truth for every creative below."
          >
            <BrandPanel
              brand={job.brandProfile}
              screenshot={job.websiteScreenshot}
              companyName={company}
              companyUrl={job.input?.companyUrl}
            />
          </Section>
        )}

        <Section
          num="02"
          label="Your ads"
          id="ads"
          title="The ads you're {em}."
          emphasis="running"
          kicker="A sample of your live Meta creative — what's in market right now."
        >
          <AdGallery
            title="Your current ads"
            subtitle="Pulled from the Meta Ad Library"
            ads={(job.companyAds || []).slice(0, 5)}
            jobId={jobId}
            totalCount={job.companyAdCount}
            videoCount={job.companyVideoCount}
            emptyMessage="No active Meta ads detected. Two likely reasons: (1) the brand isn't running on Meta right now, or (2) the brand's Facebook page name differs from the company name and our scraper couldn't bind to it. Manually checking the Meta Ad Library is the fastest sanity check. The competitor breakdown below and the diagnosis remain valid either way."
          />
        </Section>

        {job.competitorData && job.competitorData.length > 0 && (
          <Section
            num="03"
            label="Rivals"
            id="rivals"
            title="What competitors are {em}."
            emphasis="shipping"
            kicker="Top 3 active ads from each rival — the patterns that are quietly working in your category."
          >
            <CompetitorAdGallery
              competitors={job.competitorData.map((c) => ({
                ...c,
                ads: c.ads.slice(0, 3),
              }))}
              jobId={jobId}
            />
          </Section>
        )}

        {job.diagnosis && (
          <Section
            num="04"
            label="Diagnosis"
            id="diagnosis"
            title="What's actually {em}."
            emphasis="going on"
            kicker="The pattern across your ads, your rivals, and your category — and what to do about it."
          >
            <DiagnosisGrid diagnosis={job.diagnosis} />
          </Section>
        )}

        {topQuotes.length > 0 && (
          <Section
            num="05"
            label="Customer voice"
            id="voc"
            title="The words your customers {em} use."
            emphasis="actually"
            kicker="Real quotes from Reddit and review sites. Use these verbatim in headlines."
          >
            <ul className="grid gap-5 md:grid-cols-2">
              {topQuotes.map((q, i) => (
                <li
                  key={i}
                  className="rounded-md border hairline bg-paper p-6"
                >
                  <p className="font-serif text-[1.1rem] leading-relaxed text-ink/90 italic">
                    “{q.quote}”
                  </p>
                  {q.sourceLabel && (
                    <div className="mt-4 font-mono text-[0.7rem] uppercase tracking-[0.2em] text-ink/50">
                      {q.sourceLabel}
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </Section>
        )}

        {(topConcepts.length > 0 || topCreatives.length > 0) && (
          <Section
            num="06"
            label="The plan"
            id="plan"
            title="3 concepts to {em}."
            emphasis="ship next"
            kicker="Ranked by potential impact. Each concept is hook + angle + awareness stage. Mocks below."
          >
            {topConcepts.length > 0 && (
              <ConceptCards
                jobId={jobId}
                concepts={topConcepts}
                readOnly={job.status === "complete"}
              />
            )}
            {topCreatives.length > 0 && (
              <div className="mt-20 border-t hairline pt-16">
                <SubSectionHeader
                  eyebrow="Mocks"
                  title="Concepts, {em}."
                  emphasis="visualised"
                />
                <CreativeGallery
                  jobId={jobId}
                  creatives={topCreatives}
                  concepts={topConcepts}
                />
              </div>
            )}
          </Section>
        )}

        <footer className="mt-20 flex flex-col items-start justify-between gap-4 border-t hairline py-10 text-sm text-ink/55 md:flex-row md:items-center">
          <span className="font-mono text-xs">
            generated by betteryourads ·{" "}
            {job.completedAt && new Date(job.completedAt).toLocaleString()}
          </span>
          <Link href="/" className="btn-ghost-ink text-sm">
            Run another diagnosis →
          </Link>
        </footer>
      </div>
    </main>
  );
}

type StageWeight = "over" | "under" | "neglected" | "balanced";

const STAGE_DEFS: { key: string; label: string; sub: string }[] = [
  { key: "unaware", label: "Unaware", sub: "no problem yet" },
  { key: "problem", label: "Problem-aware", sub: "feels the pain" },
  { key: "solution", label: "Solution-aware", sub: "scanning options" },
  { key: "product", label: "Product-aware", sub: "comparing you vs rivals" },
  { key: "most", label: "Most-aware", sub: "ready to convert" },
];

function classifyBullet(text: string): { stageKey: string | null; weight: StageWeight; line: string } {
  const t = text.toLowerCase();
  let weight: StageWeight = "balanced";
  if (/over[- ]?represent|over[- ]?index|too much|skipping past|saturat/.test(t)) weight = "over";
  else if (/under[- ]?represent|under[- ]?index|missing|skipping|gap|not enough|minimal|under[- ]?developed/.test(t)) weight = "under";
  else if (/neglect|absent|no\s+(content|creative)|completely missing|untouched/.test(t)) weight = "neglected";

  let stageKey: string | null = null;
  for (const s of STAGE_DEFS) {
    if (t.includes(s.key)) {
      stageKey = s.key;
      break;
    }
  }
  // Tolerate variants the strategist sometimes returns
  if (!stageKey) {
    if (/most[- ]aware|bottom[- ]of[- ]funnel/.test(t)) stageKey = "most";
    else if (/top[- ]of[- ]funnel/.test(t)) stageKey = "unaware";
  }
  return { stageKey, weight, line: text };
}

function weightStyles(w: StageWeight) {
  switch (w) {
    case "over":
      return { bar: "bg-butter", dot: "bg-ink", label: "Over-represented", chipBg: "bg-butter/60", chipText: "text-ink" };
    case "under":
      return { bar: "bg-coral", dot: "bg-coral", label: "Under-represented", chipBg: "bg-coral/15", chipText: "text-coral" };
    case "neglected":
      return { bar: "bg-ink", dot: "bg-ink", label: "Neglected", chipBg: "bg-ink", chipText: "text-paper" };
    default:
      return { bar: "bg-sage", dot: "bg-sage", label: "Balanced", chipBg: "bg-sage/15", chipText: "text-sage" };
  }
}

function AwarenessStageGap({ bullets }: { bullets: string[] }) {
  const findings = bullets.map(classifyBullet);
  const stageStatus: Record<string, StageWeight> = {};
  for (const f of findings) {
    if (!f.stageKey) continue;
    // Worst-case wins (neglected > under > over > balanced)
    const ranking: StageWeight[] = ["balanced", "over", "under", "neglected"];
    const current = stageStatus[f.stageKey] ?? "balanced";
    if (ranking.indexOf(f.weight) > ranking.indexOf(current)) {
      stageStatus[f.stageKey] = f.weight;
    }
  }

  return (
    <div className="border-t hairline pt-10">
      <div className="eyebrow text-ink/55">Awareness-stage gap</div>
      <p className="mt-2 max-w-3xl text-sm text-ink/60 [text-wrap:pretty]">
        Where your creative is hitting vs where the demand actually sits. The biggest CAC leaks live in the gap.
      </p>

      {/* Funnel strip */}
      <ol className="mt-7 grid gap-2 md:grid-cols-5">
        {STAGE_DEFS.map((s, i) => {
          const w = stageStatus[s.key] ?? "balanced";
          const sty = weightStyles(w);
          return (
            <li
              key={s.key}
              className="rounded-2xl border-[1.5px] border-ink/10 bg-paper p-4"
            >
              <div className="flex items-center justify-between gap-2">
                <div className="font-mono text-[0.6rem] uppercase tracking-[0.18em] text-ink/45">
                  Stage {String(i + 1).padStart(2, "0")}
                </div>
                <span className={`grid h-2 w-2 place-items-center rounded-full ${sty.dot}`} />
              </div>
              <div className="font-semibold mt-2 text-sm text-ink">{s.label}</div>
              <div className="mt-0.5 text-[0.72rem] text-ink/55">{s.sub}</div>
              <div className={`mt-3 h-1 w-full rounded-full ${sty.bar}`} />
              <div className={`mt-3 inline-block rounded-full px-2 py-0.5 font-mono text-[0.6rem] uppercase tracking-[0.16em] ${sty.chipBg} ${sty.chipText}`}>
                {sty.label}
              </div>
            </li>
          );
        })}
      </ol>

      {/* Findings */}
      <ul className="mt-8 space-y-3">
        {findings.map((f, i) => {
          const sty = weightStyles(f.weight);
          const stageLabel = f.stageKey ? STAGE_DEFS.find((s) => s.key === f.stageKey)?.label : null;
          return (
            <li
              key={i}
              className="grid grid-cols-[auto_1fr] items-baseline gap-4 border-b hairline pb-3 last:border-0"
            >
              <span className={`inline-block rounded-full px-2 py-0.5 font-mono text-[0.6rem] uppercase tracking-[0.16em] ${sty.chipBg} ${sty.chipText}`}>
                {stageLabel ? `${stageLabel} · ${sty.label}` : sty.label}
              </span>
              <span className="text-[0.95rem] leading-[1.55] text-ink/85 [text-wrap:pretty]">
                {f.line}
              </span>
            </li>
          );
        })}
      </ul>
    </div>
  );
}

function ExecutiveSummary({ raw }: { raw: unknown }) {
  const text =
    typeof raw === "string"
      ? raw
      : Array.isArray(raw)
      ? (raw as unknown[]).map(String).join("\n")
      : String(raw ?? "");

  // The strategist often returns asterisk-bulleted prose like
  // "* Brand voice... * Current ads...". Detect that and render as a
  // scannable list. Otherwise fall back to prose.
  const cleanText = text.replace(/^["“]|["”]$/g, "").trim();
  const looksBulleted =
    /(^|\s)\*\s/.test(cleanText) ||
    /\n\s*[-•·]\s/.test(cleanText) ||
    cleanText.split(/\.\s+\*/).length >= 3;

  if (looksBulleted) {
    const bullets = cleanText
      .split(/(?:^|\s)\*\s|\n\s*[-•·]\s/)
      .map((s) => s.trim())
      .filter(Boolean)
      .map((s) =>
        s
          .replace(/\*\*(.*?)\*\*/g, "$1")
          .replace(/\*(.*?)\*/g, "$1")
          .replace(/^\s*[-•·]\s*/, "")
          .trim(),
      )
      .filter((s) => s.length > 4);

    if (bullets.length >= 2) {
      return (
        <div className="max-w-3xl">
          <div className="eyebrow text-ink/55">Executive summary</div>
          <ul className="mt-4 space-y-3">
            {bullets.map((b, i) => (
              <li
                key={i}
                className="grid grid-cols-[auto_1fr] items-baseline gap-4 border-b hairline pb-3 last:border-0"
              >
                <span className="font-mono text-[0.7rem] uppercase tracking-[0.2em] text-coral">
                  {String(i + 1).padStart(2, "0")}
                </span>
                <span className="text-[1rem] leading-[1.55] text-ink/85 md:text-[1.05rem] [text-wrap:pretty]">
                  {b}
                </span>
              </li>
            ))}
          </ul>
        </div>
      );
    }
  }

  return (
    <div className="relative max-w-3xl">
      <span className="font-serif pointer-events-none absolute -left-2 -top-8 text-7xl leading-none text-coral/60 md:-left-6 md:text-8xl">
        “
      </span>
      <p className="font-semibold text-[clamp(1.15rem,1.8vw,1.55rem)] leading-[1.35] text-ink [text-wrap:pretty]">
        {cleanText}
      </p>
    </div>
  );
}

function BrandPanel({
  brand,
  screenshot,
  companyName,
  companyUrl,
}: {
  brand?: NonNullable<Job["brandProfile"]>;
  screenshot?: string;
  companyName: string;
  companyUrl?: string;
}) {
  const colors = brand?.colors;
  const colorRoles: { key: keyof NonNullable<typeof colors>; label: string }[] = [
    { key: "primary", label: "Primary" },
    { key: "secondary", label: "Secondary" },
    { key: "accent", label: "Accent" },
    { key: "background", label: "Background" },
    { key: "text", label: "Text" },
  ];
  const headingFont = brand?.typography?.primary;
  const bodyFont = brand?.typography?.secondary || brand?.typography?.primary;
  const aesthetic = brand?.visualStyle?.aesthetic;
  const ctaShape = brand?.visualStyle?.ctaShape;

  return (
    <div className="grid gap-8 md:grid-cols-[minmax(0,1.1fr)_minmax(0,1fr)]">
      {/* Screenshot */}
      <div className="rounded-[1.3rem] border hairline bg-card overflow-hidden">
        <div className="flex items-center justify-between gap-3 border-b hairline px-5 py-3">
          <div className="min-w-0">
            <div className="eyebrow text-ink/55">Hero captured</div>
            <div className="mt-1 font-mono truncate text-sm text-ink/75">
              {companyUrl || companyName}
            </div>
          </div>
        </div>
        {screenshot ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={screenshot}
            alt={`${companyName} website hero`}
            className="block w-full bg-paper"
          />
        ) : (
          <div className="grid place-items-center bg-paper px-5 py-16 text-center text-sm text-ink/55">
            <div>
              <p>Screenshot couldn&apos;t be captured.</p>
              <p className="mt-2 text-xs text-ink/45">
                Brand colors and fonts were extracted from the raw HTML as a
                fallback, so the diagnosis is still valid.
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Colors + fonts */}
      <div className="space-y-6">
        {colors && (
          <div className="rounded-[1.3rem] border hairline bg-card p-6">
            <div className="eyebrow text-ink/55">Palette</div>
            <ul className="mt-4 space-y-3">
              {colorRoles.map(({ key, label }) => {
                const hex = colors[key];
                if (!hex) return null;
                return (
                  <li key={key} className="flex items-center gap-3">
                    <span
                      className="h-9 w-9 rounded-md border hairline"
                      style={{ backgroundColor: hex }}
                      aria-hidden
                    />
                    <div className="min-w-0 flex-1">
                      <div className="font-mono text-[0.65rem] uppercase tracking-[0.2em] text-ink/55">
                        {label}
                      </div>
                      <div className="font-mono text-sm text-ink">{hex}</div>
                    </div>
                  </li>
                );
              })}
            </ul>
          </div>
        )}

        {(headingFont || bodyFont) && (
          <div className="rounded-[1.3rem] border hairline bg-card p-6">
            <div className="eyebrow text-ink/55">Typography</div>
            <div className="mt-4 space-y-4">
              {headingFont && (
                <div>
                  <div className="font-mono text-[0.65rem] uppercase tracking-[0.2em] text-ink/55">
                    Heading
                  </div>
                  <div
                    className="mt-1 text-2xl text-ink"
                    style={{ fontFamily: `"${headingFont}", serif` }}
                  >
                    {headingFont}
                  </div>
                </div>
              )}
              {bodyFont && bodyFont !== headingFont && (
                <div>
                  <div className="font-mono text-[0.65rem] uppercase tracking-[0.2em] text-ink/55">
                    Body
                  </div>
                  <div
                    className="mt-1 text-lg text-ink"
                    style={{ fontFamily: `"${bodyFont}", sans-serif` }}
                  >
                    {bodyFont}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        {(aesthetic || ctaShape) && (
          <div className="rounded-[1.3rem] border hairline bg-card p-6">
            <div className="eyebrow text-ink/55">Style cues</div>
            <dl className="mt-4 space-y-2 text-sm">
              {aesthetic && (
                <div className="flex items-baseline justify-between gap-4">
                  <dt className="text-ink/55">Aesthetic</dt>
                  <dd className="text-ink text-right">{aesthetic}</dd>
                </div>
              )}
              {ctaShape && (
                <div className="flex items-baseline justify-between gap-4">
                  <dt className="text-ink/55">CTA shape</dt>
                  <dd className="text-ink text-right">{ctaShape}</dd>
                </div>
              )}
            </dl>
          </div>
        )}
      </div>
    </div>
  );
}

function bulletsFrom(raw: unknown, max = 6): string[] {
  const text =
    typeof raw === "string"
      ? raw
      : Array.isArray(raw)
      ? (raw as unknown[]).map(String).join("\n")
      : String(raw ?? "");
  return text
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .filter((l) => !/^[-*_]{2,}$/.test(l))
    .filter((l) => !/^#{1,6}\s/.test(l))
    .map((l) =>
      l
        .replace(/^[-*•·▸▹‣–—]\s*/, "")
        .replace(/\*\*(.*?)\*\*/g, "$1")
        .replace(/\*(.*?)\*/g, "$1")
        .trim(),
    )
    .filter((l) => l.length > 3)
    .slice(0, max);
}

function DiagnosisGrid({
  diagnosis,
}: {
  diagnosis: NonNullable<Job["diagnosis"]>;
}) {
  const panels = [
    {
      eyebrow: "What's working",
      tone: "sage" as const,
      bullets: bulletsFrom(diagnosis.doingWell),
      hint: "Keep these alive — they're the foundation.",
    },
    {
      eyebrow: "What's not",
      tone: "coral" as const,
      bullets: bulletsFrom(diagnosis.notWorking),
      hint: "Kill or rework. These are dragging spend.",
    },
    {
      eyebrow: "Rival wins to learn from",
      tone: "butter" as const,
      bullets: bulletsFrom(diagnosis.competitorWins),
      hint: "Patterns competitors print money on. Copy the structure, not the asset.",
    },
    {
      eyebrow: "Low-hanging opportunities",
      tone: "blush" as const,
      bullets: bulletsFrom(diagnosis.missingOpportunities),
      hint: "Untouched ground. Highest ROI per hour of work.",
    },
  ];

  const stage = bulletsFrom(diagnosis.awarenessStageAnalysis, 4);

  return (
    <div className="space-y-12">
      {diagnosis.executiveSummary && (
        <ExecutiveSummary raw={diagnosis.executiveSummary} />
      )}

      <div className="grid gap-5 md:grid-cols-2">
        {panels.map((p) => (
          <DiagnosisPanel key={p.eyebrow} {...p} />
        ))}
      </div>

      {stage.length > 0 && (
        <AwarenessStageGap bullets={stage} />
      )}
    </div>
  );
}

function DiagnosisPanel({
  eyebrow,
  tone,
  bullets,
  hint,
}: {
  eyebrow: string;
  tone: "sage" | "coral" | "butter" | "blush";
  bullets: string[];
  hint: string;
}) {
  const toneMap: Record<typeof tone, { bg: string; dot: string; text: string }> = {
    sage: { bg: "bg-sage/10", dot: "bg-sage", text: "text-ink" },
    coral: { bg: "bg-coral/10", dot: "bg-coral", text: "text-ink" },
    butter: { bg: "bg-butter/40", dot: "bg-ink", text: "text-ink" },
    blush: { bg: "bg-blush/40", dot: "bg-coral", text: "text-ink" },
  };
  const cls = toneMap[tone];

  if (bullets.length === 0) {
    return (
      <div className={`rounded-[1.3rem] border hairline p-6 ${cls.bg}`}>
        <div className="flex items-center gap-2">
          <span className={`h-2 w-2 rounded-full ${cls.dot}`} />
          <div className="eyebrow text-ink/55">{eyebrow}</div>
        </div>
        <p className="mt-4 text-sm text-ink/55">
          Nothing surfaced here. The strategist couldn&apos;t isolate enough signal — usually means too few ads in market.
        </p>
      </div>
    );
  }

  return (
    <div className={`rounded-[1.3rem] border hairline p-6 ${cls.bg}`}>
      <div className="flex items-center gap-2">
        <span className={`h-2 w-2 rounded-full ${cls.dot}`} />
        <div className="eyebrow text-ink/55">{eyebrow}</div>
      </div>
      <p className="mt-1 text-xs text-ink/45">{hint}</p>

      <ul className="mt-5 space-y-3">
        {bullets.map((b, i) => (
          <li
            key={i}
            className="grid grid-cols-[auto_1fr] gap-3 text-[0.92rem] leading-[1.5] text-ink/85"
          >
            <span className={`mt-2 h-1 w-1 shrink-0 rounded-full ${cls.dot}`} />
            <span>{b}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

function TldrInline({ tldr }: { tldr: unknown }) {
  const raw =
    typeof tldr === "string"
      ? tldr
      : Array.isArray(tldr)
      ? (tldr as unknown[]).map(String).join("\n")
      : String(tldr ?? "");

  const bullets = raw
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .filter((l) => !/^[-*_]{2,}$/.test(l))
    .map((l) => l.replace(/^[-*•·▸▹‣–—]\s*/, "").replace(/\*\*/g, "").trim())
    .filter((l) => l.length > 0)
    .slice(0, 3);

  if (bullets.length === 0) return null;

  return (
    <ol className="mt-10 max-w-2xl space-y-3">
      {bullets.map((b, i) => (
        <li
          key={i}
          className="grid grid-cols-[auto_1fr] items-baseline gap-4 border-b hairline pb-3 last:border-0"
        >
          <span className="font-mono text-[0.7rem] uppercase tracking-[0.2em] text-coral">
            {String(i + 1).padStart(2, "0")}
          </span>
          <span className="text-[1rem] leading-[1.55] text-ink/85 md:text-[1.05rem]">
            {b}
          </span>
        </li>
      ))}
    </ol>
  );
}

function ProgressRail({ activeId }: { activeId: string }) {
  const activeIndex = Math.max(
    0,
    SECTIONS.findIndex((s) => s.id === activeId)
  );
  const progress = ((activeIndex + 1) / SECTIONS.length) * 100;

  return (
    <aside
      aria-label="Report progress"
      className="pointer-events-none fixed left-4 top-1/2 z-10 hidden -translate-y-1/2 2xl:block"
    >
      <div className="pointer-events-auto flex flex-col items-start gap-2">
        <ol className="space-y-1.5">
          {SECTIONS.map((s) => {
            const active = s.id === activeId;
            const done =
              SECTIONS.findIndex((x) => x.id === s.id) < activeIndex;
            return (
              <li key={s.id}>
                <a
                  href={`#${s.id}`}
                  className="group flex items-center gap-2.5 py-1 transition"
                  aria-current={active ? "true" : undefined}
                >
                  <span
                    className={`block h-[2px] transition-all duration-500 ${
                      active
                        ? "w-7 bg-coral"
                        : done
                        ? "w-4 bg-ink/40"
                        : "w-3 bg-ink/15 group-hover:bg-ink/40"
                    }`}
                  />
                  <span
                    className={`font-mono text-[0.62rem] uppercase tracking-[0.18em] transition-opacity ${
                      active
                        ? "text-ink"
                        : done
                        ? "text-ink/55"
                        : "text-ink/30 group-hover:text-ink/60"
                    }`}
                  >
                    {s.label}
                  </span>
                </a>
              </li>
            );
          })}
        </ol>

        <div className="mt-2 flex items-center gap-2 pl-[0.15rem]">
          <div className="h-[2px] w-12 overflow-hidden bg-hairline">
            <div
              className="h-full bg-coral transition-all duration-700 ease-out"
              style={{ width: `${progress}%` }}
            />
          </div>
          <span className="font-mono text-[0.6rem] tabular-nums text-ink/45">
            {activeIndex + 1}/{SECTIONS.length}
          </span>
        </div>
      </div>
    </aside>
  );
}

function SubSectionHeader({
  eyebrow,
  title,
  emphasis,
  id,
}: {
  eyebrow: string;
  title: string;
  emphasis?: string;
  id?: string;
}) {
  const [before, after] = emphasis && title.includes("{em}")
    ? title.split("{em}")
    : [title, ""];
  return (
    <header id={id} className="mb-12">
      <div className="eyebrow text-ink/55">{eyebrow}</div>
      <h3 className="display mt-3 text-[clamp(1.75rem,3.4vw,2.75rem)] leading-[1.05] [text-wrap:balance]">
        {before}
        {emphasis && <span className="display-italic text-coral">{emphasis}</span>}
        {after}
      </h3>
    </header>
  );
}

function Section({
  num,
  label,
  id,
  tone = "paper",
  title,
  emphasis,
  kicker,
  children,
}: {
  num: string;
  label: string;
  id: string;
  tone?: "paper" | "blush";
  title?: string;
  emphasis?: string;
  kicker?: string;
  children: React.ReactNode;
}) {
  const toneWrap =
    tone === "blush"
      ? "relative -mx-5 bg-blush px-5 md:-mx-10 md:px-10"
      : "";

  const [before, after] = title && emphasis && title.includes("{em}")
    ? title.split("{em}")
    : [title ?? "", ""];

  return (
    <section id={id} data-reveal className={`py-20 md:py-28 ${toneWrap}`}>
      <header className="mb-12 md:mb-16">
        <div className="grid grid-cols-[auto_1fr] items-start gap-6 md:gap-10">
          <span className="font-semibold text-6xl leading-[0.9] text-coral md:text-7xl">
            {num}
          </span>
          <div className="min-w-0 border-l hairline pl-6 md:pl-10">
            <div className="font-mono text-[0.72rem] uppercase tracking-[0.22em] text-ink/55">
              {label}
            </div>
            {title && (
              <h2 className="display mt-3 text-[clamp(2rem,4.2vw,3.75rem)] leading-[1.02] [text-wrap:balance]">
                {before}
                {emphasis && (
                  <span className="display-italic text-coral">{emphasis}</span>
                )}
                {after}
              </h2>
            )}
            {kicker && (
              <p className="mt-5 max-w-2xl text-[1rem] leading-relaxed text-ink/65 md:text-[1.05rem] [text-wrap:pretty]">
                {kicker}
              </p>
            )}
          </div>
        </div>
      </header>
      {children}
    </section>
  );
}
