"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { ProgressTracker } from "@/components/ProgressTracker";
import { AdGallery, CompetitorAdGallery } from "@/components/AdGallery";
import { ConceptCards } from "@/components/ConceptCards";
import { CreativeGallery } from "@/components/CreativeGallery";
import type { Job } from "@/lib/types";

// 1-pager view. Heavy reports (full brand profile, exhaustive VoC, multi-
// field diagnosis prose) are still generated by the pipeline and live on
// the Job — they just aren't surfaced here. Once auth/dashboard is in
// (Phase 3+), the deep view is a click away. This page = the agency
// hand-off that founders actually read.
const SECTIONS: { id: string; num: string; label: string }[] = [
  { id: "ads", num: "01", label: "Your ads" },
  { id: "rivals", num: "02", label: "Rivals" },
  { id: "voc", num: "03", label: "Customer voice" },
  { id: "plan", num: "04", label: "The plan" },
];

export default function AnalyzePage() {
  const params = useParams();
  const jobId = params.jobId as string;
  const isMockJob = jobId.startsWith("mock-");
  const [job, setJob] = useState<Job | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [activeId, setActiveId] = useState<string>("ads");
  const [now, setNow] = useState(() => Date.now());
  const rootRef = useRef<HTMLElement | null>(null);
  const advancingRef = useRef(false);

  const fetchJob = useCallback(async () => {
    try {
      const res = await fetch(`/api/jobs/${jobId}`);
      if (!res.ok) {
        setError("Job not found");
        return;
      }
      const data = await res.json();
      setJob(data);
    } catch {
      setError("Failed to fetch job status");
    }
  }, [jobId]);

  useEffect(() => {
    fetchJob();
    const clock = setInterval(() => setNow(Date.now()), 1000);
    const interval = setInterval(() => {
      if (
        job?.status === "complete" ||
        job?.status === "awaiting-approval" ||
        job?.status === "error"
      ) {
        clearInterval(interval);
        return;
      }
      fetchJob();
    }, 2000);
    return () => {
      clearInterval(clock);
      clearInterval(interval);
    };
  }, [fetchJob, job?.status]);

  useEffect(() => {
    if (
      !job ||
      job.status === "complete" ||
      job.status === "awaiting-approval" ||
      job.status === "error" ||
      isMockJob ||
      advancingRef.current
    ) {
      return;
    }

    const justStartedScanner =
      job.status === "scraping-website" &&
      job.progress.length <= 1 &&
      Date.now() - new Date(job.createdAt).getTime() < 10_000;
    if (justStartedScanner) return;

    let cancelled = false;
    const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

    async function advanceUntilDone() {
      advancingRef.current = true;
      try {
        while (!cancelled) {
          const res = await fetch(`/api/jobs/${jobId}/advance`, {
            method: "POST",
          });
          const data = (await res.json().catch(() => ({}))) as {
            done?: boolean;
            status?: Job["status"];
          };

          await fetchJob();

          if (
            !res.ok ||
            data.done ||
            data.status === "complete" ||
            data.status === "awaiting-approval" ||
            data.status === "error"
          ) {
            break;
          }

          await delay(250);
        }
      } catch (err) {
        console.error("[analyze] advance failed; polling will keep retrying", err);
        await delay(2000);
      } finally {
        advancingRef.current = false;
      }
    }

    void advanceUntilDone();
    return () => {
      cancelled = true;
    };
  }, [fetchJob, isMockJob, job, jobId]);

  useEffect(() => {
    if (job?.status !== "complete" && job?.status !== "awaiting-approval") return;
    const root = rootRef.current;
    if (!root) return;

    const revealTargets = root.querySelectorAll<HTMLElement>("[data-reveal]");
    const revealIO = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.isIntersecting) {
            e.target.classList.add("in-view");
            revealIO.unobserve(e.target);
          }
        }
      },
      { rootMargin: "0px 0px -15% 0px", threshold: 0.12 }
    );
    revealTargets.forEach((el) => revealIO.observe(el));

    const activeTargets = SECTIONS.map((s) =>
      document.getElementById(s.id)
    ).filter((el): el is HTMLElement => !!el);
    const activeIO = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((e) => e.isIntersecting)
          .sort((a, b) => (a.target as HTMLElement).offsetTop - (b.target as HTMLElement).offsetTop);
        if (visible[0]) setActiveId(visible[0].target.id);
      },
      { rootMargin: "-40% 0px -50% 0px", threshold: 0 }
    );
    activeTargets.forEach((el) => activeIO.observe(el));

    return () => {
      revealIO.disconnect();
      activeIO.disconnect();
    };
  }, [job?.status]);

  if (error) {
    return (
      <main className="min-h-screen bg-paper flex items-center justify-center">
        <div className="text-center">
          <div className="eyebrow text-ink/60">404</div>
          <h1 className="font-semibold mt-3 text-4xl">We couldn’t find that job.</h1>
          <p className="mt-3 text-ink/60">{error}</p>
          <Link href="/" className="btn-chunk mt-6 inline-flex">← Start a new diagnosis</Link>
        </div>
      </main>
    );
  }

  if (!job) {
    return (
      <main className="min-h-screen bg-paper flex items-center justify-center">
        <div className="h-5 w-5 animate-spin rounded-full border-2 border-coral border-t-transparent" />
      </main>
    );
  }

  if (job.status !== "complete" && job.status !== "awaiting-approval") {
    return (
      <main className="min-h-screen bg-paper">
        <div className="mx-auto max-w-2xl px-4">
          <ProgressTracker
            jobId={job.id}
            status={job.status}
            progress={job.progress}
            error={job.error}
            now={now}
          />
        </div>
      </main>
    );
  }

  const company = job.input?.companyName || "this company";
  const topConcepts = (job.concepts || []).slice(0, 3);
  const topCreatives = (job.creatives || []).slice(0, 3);
  const topQuotes = (job.voc?.snippets || []).slice(0, 4);

  return (
    <main ref={rootRef} className="min-h-screen bg-paper text-ink">
      <ProgressRail activeId={activeId} />

      <header className="sticky top-0 z-20 border-b hairline bg-paper/85 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-6 px-5 py-4">
          <Link href="/" className="flex items-baseline gap-[2px] font-serif text-[1.15rem] leading-none">
            <span className="italic">better</span>
            <span className="italic text-coral">your</span>
            <span className="italic">ads</span>
            <span className="ml-1 inline-block h-1.5 w-1.5 translate-y-[-2px] rounded-full bg-coral" />
          </Link>
          <div className="hidden flex-1 items-baseline gap-3 md:flex">
            <span className="font-mono text-[0.7rem] uppercase tracking-[0.2em] text-ink/45">
              analysis for
            </span>
            <span className="font-semibold text-lg text-ink">{company}</span>
          </div>
          <nav className="hidden items-center gap-6 text-sm md:flex">
            {SECTIONS.map((s) => (
              <a
                key={s.id}
                href={`#${s.id}`}
                className="link-underline text-ink/70 hover:text-ink"
              >
                {s.label}
              </a>
            ))}
          </nav>
        </div>
      </header>

      {/* Verdict masthead — the whole diagnosis in 4 lines */}
      <section data-reveal className="border-b hairline">
        <div className="mx-auto max-w-6xl px-5 py-16 md:py-24">
          <div className="eyebrow text-ink/55">
            The verdict · {new Date(job.completedAt || Date.now()).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" })}
          </div>
          <h1 className="display mt-5 max-w-4xl text-[clamp(2.5rem,6vw,5.25rem)]">
            What’s happening with{" "}
            <span className="display-italic text-coral">{company}</span>’s ads.
          </h1>
          {job.diagnosis?.tldr && <TldrInline tldr={job.diagnosis.tldr} />}
        </div>
      </section>

      <div className="mx-auto max-w-6xl px-5">
        <Section
          num="01"
          label="Your ads"
          id="ads"
          title="The ads you're {em}."
          emphasis="running"
          kicker="A sample of your live Meta creative — what's in market right now."
        >
          <AdGallery
            title="Your current ads"
            subtitle="Pulled from the Meta Ad Library"
            ads={(job.companyAds || []).slice(0, 5)}
            jobId={jobId}
            totalCount={job.companyAdCount}
            videoCount={job.companyVideoCount}
            emptyMessage="No active Meta ads found for this brand. Likely they're not running on Meta right now — many B2B brands focus their spend on LinkedIn or Google. The competitor breakdown below is still relevant for spotting what's working in your category."
          />
        </Section>

        {job.competitorData && job.competitorData.length > 0 && (
          <Section
            num="02"
            label="Rivals"
            id="rivals"
            title="What competitors are {em}."
            emphasis="shipping"
            kicker="Top 3 active ads from each rival — the patterns that are quietly working in your category."
          >
            <CompetitorAdGallery
              competitors={job.competitorData.map((c) => ({
                ...c,
                ads: c.ads.slice(0, 3),
              }))}
              jobId={jobId}
            />
          </Section>
        )}

        {topQuotes.length > 0 && (
          <Section
            num="03"
            label="Customer voice"
            id="voc"
            title="The words your customers {em} use."
            emphasis="actually"
            kicker="Real quotes from Reddit and review sites. Use these verbatim in headlines."
          >
            <ul className="grid gap-5 md:grid-cols-2">
              {topQuotes.map((q, i) => (
                <li
                  key={i}
                  className="rounded-md border hairline bg-paper p-6"
                >
                  <p className="font-serif text-[1.1rem] leading-relaxed text-ink/90 italic">
                    “{q.quote}”
                  </p>
                  {q.sourceLabel && (
                    <div className="mt-4 font-mono text-[0.7rem] uppercase tracking-[0.2em] text-ink/50">
                      {q.sourceLabel}
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </Section>
        )}

        {(topConcepts.length > 0 || topCreatives.length > 0) && (
          <Section
            num="04"
            label="The plan"
            id="plan"
            title="3 concepts to {em}."
            emphasis="ship next"
            kicker="Ranked by potential impact. Each concept is hook + angle + awareness stage. Mocks below."
          >
            {topConcepts.length > 0 && (
              <ConceptCards
                jobId={jobId}
                concepts={topConcepts}
                readOnly={job.status === "complete"}
              />
            )}
            {topCreatives.length > 0 && (
              <div className="mt-20 border-t hairline pt-16">
                <SubSectionHeader
                  eyebrow="Mocks"
                  title="Concepts, {em}."
                  emphasis="visualised"
                />
                <CreativeGallery
                  jobId={jobId}
                  creatives={topCreatives}
                  concepts={topConcepts}
                />
              </div>
            )}
          </Section>
        )}

        <footer className="mt-20 flex flex-col items-start justify-between gap-4 border-t hairline py-10 text-sm text-ink/55 md:flex-row md:items-center">
          <span className="font-mono text-xs">
            generated by betteryourads ·{" "}
            {job.completedAt && new Date(job.completedAt).toLocaleString()}
          </span>
          <Link href="/" className="btn-ghost-ink text-sm">
            Run another diagnosis →
          </Link>
        </footer>
      </div>
    </main>
  );
}

function TldrInline({ tldr }: { tldr: unknown }) {
  const raw =
    typeof tldr === "string"
      ? tldr
      : Array.isArray(tldr)
      ? (tldr as unknown[]).map(String).join("\n")
      : String(tldr ?? "");

  const bullets = raw
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .filter((l) => !/^[-*_]{2,}$/.test(l))
    .map((l) => l.replace(/^[-*•·▸▹‣–—]\s*/, "").replace(/\*\*/g, "").trim())
    .filter((l) => l.length > 0)
    .slice(0, 3);

  if (bullets.length === 0) return null;

  return (
    <ol className="mt-10 max-w-2xl space-y-3">
      {bullets.map((b, i) => (
        <li
          key={i}
          className="grid grid-cols-[auto_1fr] items-baseline gap-4 border-b hairline pb-3 last:border-0"
        >
          <span className="font-mono text-[0.7rem] uppercase tracking-[0.2em] text-coral">
            {String(i + 1).padStart(2, "0")}
          </span>
          <span className="text-[1rem] leading-[1.55] text-ink/85 md:text-[1.05rem]">
            {b}
          </span>
        </li>
      ))}
    </ol>
  );
}

function ProgressRail({ activeId }: { activeId: string }) {
  const activeIndex = Math.max(
    0,
    SECTIONS.findIndex((s) => s.id === activeId)
  );
  const progress = ((activeIndex + 1) / SECTIONS.length) * 100;

  return (
    <aside
      aria-label="Report progress"
      className="pointer-events-none fixed left-4 top-1/2 z-10 hidden -translate-y-1/2 2xl:block"
    >
      <div className="pointer-events-auto flex flex-col items-start gap-2">
        <ol className="space-y-1.5">
          {SECTIONS.map((s) => {
            const active = s.id === activeId;
            const done =
              SECTIONS.findIndex((x) => x.id === s.id) < activeIndex;
            return (
              <li key={s.id}>
                <a
                  href={`#${s.id}`}
                  className="group flex items-center gap-2.5 py-1 transition"
                  aria-current={active ? "true" : undefined}
                >
                  <span
                    className={`block h-[2px] transition-all duration-500 ${
                      active
                        ? "w-7 bg-coral"
                        : done
                        ? "w-4 bg-ink/40"
                        : "w-3 bg-ink/15 group-hover:bg-ink/40"
                    }`}
                  />
                  <span
                    className={`font-mono text-[0.62rem] uppercase tracking-[0.18em] transition-opacity ${
                      active
                        ? "text-ink"
                        : done
                        ? "text-ink/55"
                        : "text-ink/30 group-hover:text-ink/60"
                    }`}
                  >
                    {s.label}
                  </span>
                </a>
              </li>
            );
          })}
        </ol>

        <div className="mt-2 flex items-center gap-2 pl-[0.15rem]">
          <div className="h-[2px] w-12 overflow-hidden bg-hairline">
            <div
              className="h-full bg-coral transition-all duration-700 ease-out"
              style={{ width: `${progress}%` }}
            />
          </div>
          <span className="font-mono text-[0.6rem] tabular-nums text-ink/45">
            {activeIndex + 1}/{SECTIONS.length}
          </span>
        </div>
      </div>
    </aside>
  );
}

function SubSectionHeader({
  eyebrow,
  title,
  emphasis,
  id,
}: {
  eyebrow: string;
  title: string;
  emphasis?: string;
  id?: string;
}) {
  const [before, after] = emphasis && title.includes("{em}")
    ? title.split("{em}")
    : [title, ""];
  return (
    <header id={id} className="mb-12">
      <div className="eyebrow text-ink/55">{eyebrow}</div>
      <h3 className="display mt-3 text-[clamp(1.75rem,3.4vw,2.75rem)] leading-[1.05] [text-wrap:balance]">
        {before}
        {emphasis && <span className="display-italic text-coral">{emphasis}</span>}
        {after}
      </h3>
    </header>
  );
}

function Section({
  num,
  label,
  id,
  tone = "paper",
  title,
  emphasis,
  kicker,
  children,
}: {
  num: string;
  label: string;
  id: string;
  tone?: "paper" | "blush";
  title?: string;
  emphasis?: string;
  kicker?: string;
  children: React.ReactNode;
}) {
  const toneWrap =
    tone === "blush"
      ? "relative -mx-5 bg-blush px-5 md:-mx-10 md:px-10"
      : "";

  const [before, after] = title && emphasis && title.includes("{em}")
    ? title.split("{em}")
    : [title ?? "", ""];

  return (
    <section id={id} data-reveal className={`py-20 md:py-28 ${toneWrap}`}>
      <header className="mb-12 md:mb-16">
        <div className="grid grid-cols-[auto_1fr] items-start gap-6 md:gap-10">
          <span className="font-semibold text-6xl leading-[0.9] text-coral md:text-7xl">
            {num}
          </span>
          <div className="min-w-0 border-l hairline pl-6 md:pl-10">
            <div className="font-mono text-[0.72rem] uppercase tracking-[0.22em] text-ink/55">
              {label}
            </div>
            {title && (
              <h2 className="display mt-3 text-[clamp(2rem,4.2vw,3.75rem)] leading-[1.02] [text-wrap:balance]">
                {before}
                {emphasis && (
                  <span className="display-italic text-coral">{emphasis}</span>
                )}
                {after}
              </h2>
            )}
            {kicker && (
              <p className="mt-5 max-w-2xl text-[1rem] leading-relaxed text-ink/65 md:text-[1.05rem]">
                {kicker}
              </p>
            )}
          </div>
        </div>
      </header>
      {children}
    </section>
  );
}
