"use client";

const STAGE_TONE: Record<string, { bg: string; ink: string }> = {
  unaware:         { bg: "bg-blush",  ink: "text-ink" },
  "problem aware": { bg: "bg-coral",  ink: "text-white" },
  "solution aware":{ bg: "bg-butter", ink: "text-ink" },
  "product aware": { bg: "bg-sage",   ink: "text-white" },
  "most aware":    { bg: "bg-ink",    ink: "text-paper" },
};

function getStageTone(stage: string) {
  const lower = stage.toLowerCase();
  for (const [key, tone] of Object.entries(STAGE_TONE)) {
    if (lower.includes(key)) return tone;
  }
  return { bg: "bg-ink/10", ink: "text-ink" };
}

interface ParsedConcept {
  name: string;
  stage: string;
  angle: string;
  hookDirection: string;
  proofStyle: string;
  whyThisConcept: string;
  whatItLooksLike: string;
}

function parseConcepts(raw: string): ParsedConcept[] {
  const concepts: ParsedConcept[] = [];
  const match = raw.match(/###\s+Concept\s+\d+:[\s\S]*/i);
  if (!match) return [];

  const parts = match[0]
    .split(/###\s+Concept\s+\d+:\s*/i)
    .map((p) => p.trim())
    .filter((p) => p.length > 0);

  for (const part of parts) {
    const lines = part.split("\n");
    const name =
      lines[0]?.replace(/^#+\s*/, "").replace(/\*\*/g, "").trim() ||
      "Untitled Concept";

    const getField = (label: string): string => {
      const line = lines.find((l) =>
        l.toLowerCase().includes(`**${label.toLowerCase()}`)
      );
      if (!line) return "";
      return line.replace(/^.*?\*\*.*?\*\*:?\s*/i, "").trim();
    };

    concepts.push({
      name,
      stage: getField("awareness stage"),
      angle: getField("angle"),
      hookDirection: getField("hook direction"),
      proofStyle: getField("proof style"),
      whyThisConcept: getField("why this concept"),
      whatItLooksLike: getField("what it looks like"),
    });
  }

  return concepts;
}

function parseTestPlan(raw: string): { heading?: string; text: string }[] {
  if (!raw) return [];
  return raw
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .filter((l) => !/^[-*_]{3,}$/.test(l))
    .filter((l) => !/^\*?This analysis was generated by/i.test(l))
    .map((line) => {
      const m = line.match(/^[-*]?\s*\*\*(.+?):\*\*\s*(.*)$/);
      if (m) return { heading: m[1].trim(), text: m[2].replace(/\*\*/g, "").trim() };
      return { text: line.replace(/^[-*]\s*/, "").replace(/\*\*/g, "").trim() };
    });
}

export function ConceptCards({
  conceptsRaw,
  testPlanRaw,
}: {
  conceptsRaw: string;
  testPlanRaw: string;
}) {
  const concepts = parseConcepts(conceptsRaw);
  const allocation = conceptsRaw
    .match(/Allocation rationale:\s*([^\n]+)/i)?.[1]
    ?.replace(/\*\*/g, "")
    ?.trim();

  const testPlan = parseTestPlan(testPlanRaw);

  return (
    <div className="space-y-16">
      {/* Opening — like a prescription header */}
      <div className="max-w-3xl">
        <div className="eyebrow text-coral">The play</div>
        <h3 className="display mt-4 text-[clamp(2rem,4vw,3.25rem)]">
          So here’s <span className="display-italic text-coral">what to ship</span>.
        </h3>
        {allocation && (
          <p className="mt-5 font-serif text-xl italic leading-relaxed text-ink/75">
            {allocation}
          </p>
        )}
      </div>

      {/* Concepts as an editorial index. Each row is a native <details>
          element — click to unfold the strategist's reasoning inline. */}
      <ol className="divide-y divide-hairline border-y hairline">
        {concepts.map((c, i) => {
          const tone = getStageTone(c.stage);
          return (
            <li key={i}>
              <details className="concept group">
                <summary className="grid grid-cols-[3rem_1fr_auto] items-center gap-4 py-7 md:grid-cols-[5rem_8rem_1fr_auto] md:gap-8">
                  <span className="font-serif text-4xl italic leading-none text-coral md:text-5xl">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <span>
                    {c.stage && (
                      <span className={`inline-block rounded-full border-[1.5px] border-ink px-2.5 py-1 font-mono text-[0.6rem] uppercase tracking-widest ${tone.bg} ${tone.ink}`}>
                        {c.stage}
                      </span>
                    )}
                  </span>
                  <h4 className="col-span-3 font-serif text-[clamp(1.25rem,2.2vw,1.9rem)] italic leading-[1.2] text-ink md:col-span-1">
                    {c.name}
                  </h4>
                  <span className="flex h-9 w-9 items-center justify-center rounded-full border-[1.5px] border-ink/20 text-ink/60 transition group-hover:border-ink group-hover:text-ink">
                    <span className="caret inline-block">→</span>
                  </span>
                </summary>

                <div className="concept-body">
                  <div>
                    <div className="pb-8 md:grid md:grid-cols-[5rem_8rem_1fr] md:gap-8">
                      <div className="hidden md:block" />
                      <div className="hidden md:block" />
                      <div>
                        <dl className="grid grid-cols-1 gap-4 sm:grid-cols-3">
                          {c.angle && <Field label="Angle" value={c.angle} />}
                          {c.hookDirection && <Field label="Hook" value={c.hookDirection} />}
                          {c.proofStyle && <Field label="Proof" value={c.proofStyle} />}
                        </dl>

                        {(c.whyThisConcept || c.whatItLooksLike) && (
                          <div className="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2">
                            {c.whyThisConcept && (
                              <Longform label="Why" text={c.whyThisConcept} />
                            )}
                            {c.whatItLooksLike && (
                              <Longform label="What it looks like" text={c.whatItLooksLike} />
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              </details>
            </li>
          );
        })}
      </ol>

      {/* Test plan — prescription ribbon */}
      {testPlan.length > 0 && (
        <div className="relative -mx-5 bg-ink px-5 py-10 text-paper md:-mx-10 md:px-10 md:py-14">
          <div aria-hidden className="pointer-events-none absolute inset-0 opacity-[0.06] paper-grain" />
          <div className="relative mx-auto max-w-5xl">
            <div className="flex items-baseline justify-between gap-4">
              <div className="eyebrow text-paper/55">The test plan</div>
              <div className="font-mono text-[0.7rem] uppercase tracking-[0.2em] text-paper/45">
                week one →
              </div>
            </div>
            <ul className="mt-6 grid grid-cols-1 gap-5 md:grid-cols-2">
              {testPlan.map((t, i) => (
                <li key={i} className="border-l-[2px] border-coral pl-4">
                  {t.heading && (
                    <div className="font-serif text-xl italic text-paper">
                      {t.heading}
                    </div>
                  )}
                  <div className={`${t.heading ? "mt-1 text-paper/75" : "text-paper"} text-[0.95rem] leading-relaxed`}>
                    {t.text}
                  </div>
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="eyebrow text-ink/50">{label}</dt>
      <dd className="mt-1 text-[0.95rem] leading-relaxed text-ink">{value}</dd>
    </div>
  );
}

function Longform({ label, text }: { label: string; text: string }) {
  return (
    <div className="rounded-xl bg-paper/50 p-4">
      <div className="eyebrow text-ink/50">{label}</div>
      <p className="mt-2 text-[0.95rem] leading-relaxed text-ink/85">{text}</p>
    </div>
  );
}
